name = "Technetium"
author = "Aeris1One"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960fc17e59e6fe95e23bd6f9c4039f444361e6bc475bf5f16be2797c9e9c914b"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
