name = "Technetium"
author = "Aeris1One"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "761781bdc96395cd4a492b7a8824ed26bc898ff212c9fdc421ae03c6ee633cf6"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
