name = "Technetium"
author = "Aeris1One"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "defdcae47b2398c12f370a0fbd506c21cf9052a4c0a0dba02d79466c50fcea05"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
