name = "Technetium"
author = "Aeris1One"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a208555cdd9d06b56a653d205b2e5ba6b87d3077a71733f6be0af8d64df0886a"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
