name = "Technetium"
author = "Aeris1One"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdffdb84a24cf9df64e27873707a0cc1f984c436e3ded77cd2bd04f868d7d244"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
