name = "Technetium"
author = "Aeris1One"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be47a29efa573394ec29ba7bec553dff890c895529e5221268644ffa18b79854"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
